### ISSUE TITLE
Rollback with uncommited changes issue

### ISSUE THREAD

**Issue by addatwork** [banago/PHPloy#101] opened 2015-03-17 14:29 UTC
I was surprised to find that PHPloy sent a work-in-progress copy of a file to the production server.
It sends the list of files correctly, but the content of the file is the current state of the files regardless of the state they were in when the commit took place.

- have a test.txt
- commit
- push
- change the content of test.txt
- phploy 

it will upload the modified version of test.txt.

Is this the desired behavior?

**Comment by NathanGiesbrecht** [comment] 2015-03-18 15:38
I'm not certain, but I do believe that is the intended behavior. The alternative would be to reset your project to the last commit state, in which case you'd lose any work you'd done since your last commit - which is obviously NOT desirable. 

That said, I do see your point in that only committed changes should be deployed. Perhaps something like doing an automatic `git stash`, then deploy, then `git pop` to restore the working state would be something worth considering? I'll wait to hear what @banago has to say on the matter.

**Comment by addatwork** [comment] 2015-03-18 15:41
Seems weird since PHPloy is capable of rollbacks, meaning it uploads versions of files from a repo, not from the machine is ran from.

**Comment by banago** [comment] 2015-03-24 18:35
@addatwork, as @NathanGiesbrecht is pointing out, that is not the intended behavior. PHPloy on every rollback, reverts the whole project to the point you are rolling back to. In this particular case, it might have been that the revert has failed because you had uncommitted changes that might be lost, so no revert has happened on the repo at all. I'll have to test it with uncommented changes, which I have not, to determine it. Thanks for pointing this out.

**Closed** 2015-04-26 08:47 UTC
