### ISSUE TITLE
phploy --sync not working

### ISSUE THREAD

**Issue by shekki25** [banago/PHPloy#221] opened 2016-04-01 17:53 UTC
`phploy --sync` command not working as intended on 4.0 stable. It tries to run phploy as if there were no arguments.

**Comment by dl1ely** [comment] 2016-04-01 21:06
Argument parsing seems to have a problem:
Notice: Undefined offset: 1 in …\PHPloy\vendor\league\climate\src\Argument\Parser.php on line 195

So the sync option is not recognized. Looking into it.

**Comment by dl1ely** [comment] 2016-04-01 22:00
Hmm, there is some deeper problem in using the argument parsing library. Both --sync and --rollback need arguments in the form of `--sync=[SHA1 hash]` or `--sync [SHA1 hash]`. Only `--sync` or `--rollback` does not work, and the argument parsing library does NOT return the defaultValues ("LAST" for sync and "HEAD^" for rollback) as @banago seem to expect it. I do not know where the fault is, guessing from the sparse docs at http://climate.thephpleague.com/arguments/ i would also expect to work the defaultValues like that. But they don't.

What works is `--sync=sync` to set the .revision file to the current SHA1 of the repo, or `--sync=[SHA1]` to set the file to a specific SHA1. Do NOT use `--sync=LAST`, as the defaultValue suggests: It sets .revision to the string "LAST", and all subsequent deploy tries will fail with `Oh Snap: Unsupported git-diff status: f`. Only deleting .revision and starting fresh will fix that.

Same for rollback: Use `--rollback=[commit id]`, with the commit id being a SHA1 or HEAD~, HEAD^ and so on. On Windows, HEAD^ does not work, the ^ does not get parsed, the value will be HEAD. Also, there seem to be a problem with deleted files when rolling back. I cannot roll back my testrepo.

So, `--sync=…` is rather dangerous as you can easily screw up your .revision file, but `--sync=sync` works as `--sync` should according to the readme.md. `--rollback=…` needs a concrete commit id, and seems to have problems nonetheless. 

Perhaps @banago can make it work as described in readme.md, or update the readme to the current behaviour. Setting an arbitrary string as SHA1 in .revision on the server seems to be a rather dangerous option for me, at least the argument should be a valid SHA1 hash. On top of that, rollback seems to need some more testing.

**Comment by banago** [comment] 2016-04-01 22:13
@dl1ely you are perfectly right. It seems to be a flysystem issue because this did not happen when I initially implemented it. I'll update PHPloy to fix the sync/LAST discrapency, so it will accept `--sync=LAST` as expected.

**Comment by dl1ely** [comment] 2016-04-01 22:18
@banago But CLImate Argument Parser does not seem to support the defaultValue values, so `--sync` will not work like `--sync=LAST`, although defaultValue => 'LAST' is set. Do you know why? A regression in the argument parser?

**Comment by banago** [comment] 2016-04-01 22:23
@dl1ely, yes, my best guess is a regression in the argument parser.

**Comment by banago** [comment] 2016-04-01 22:34
@dl1ely filed an issue here: https://github.com/thephpleague/climate/issues/84 Please add your thoughts there if you think I've missed something.

**Comment by dl1ely** [comment] 2016-04-01 22:36
I tried looking into the parser to find out when and where defaultValue gets used, but i could not make sense out of it.

**Comment by shekki25** [comment] 2016-04-02 16:49
Thanks @dl1ely and @banago!

**Comment by banago** [comment] 2016-04-04 21:04
@shekki25 this is now fixed. Thanks for reporting it. Enjoy!

**Closed by banago** 2016-04-04 21:04 UTC
Labels: bug
